### ISSUE TITLE
0.10.14 is not working, 0.10.12 still works ok

### ISSUE THREAD

**Issue by triatic** [trevorhobenshield/twitter-api-client#152]
```
Traceback (most recent call last):
  File "/home/ubuntu/twitter/twitter_search.py", line 25, in <module>
    results = tclientSc.tweets([xxx, xxx, xxx, xxx, xxx], limit=10)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/twitter/lib/python3.11/site-packages/twitter/scraper.py", line 92, in tweets
    return self._run(Operation.UserTweets, user_ids, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/twitter/lib/python3.11/site-packages/twitter/scraper.py", line 538, in _run
    res = asyncio.run(self._process(operation, _queries, **kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/twitter/lib/python3.11/site-packages/nest_asyncio.py", line 27, in run
    loop = asyncio.get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/twitter/lib/python3.11/site-packages/nest_asyncio.py", line 41, in _get_event_loop
    loop = events.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/twitter/lib/python3.11/site-packages/nest_asyncio.py", line 68, in get_event_loop
    _patch_loop(loop)
  File "/home/ubuntu/twitter/lib/python3.11/site-packages/nest_asyncio.py", line 184, in _patch_loop
    raise ValueError('Can\'t patch loop of type %s' % type(loop))
ValueError: Can't patch loop of type <class 'uvloop.Loop'>
sys:1: RuntimeWarning: coroutine 'Scraper._process' was never awaited

```

**Comment by trevorhobenshield** [comment]
Can't replicate this issue on Arch or Windows. I didn't test on debian-based distros this time (although that shouldn't matter in this context). I reverted some of the uvloop and nest_asyncio initialization. Hopefully that resolves the issue.

**Comment by triatic** [comment]
Thank you, 0.10.15 works fine.
