### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'debug'

### ISSUE THREAD

**Issue by echan00** [trevorhobenshield/twitter-api-client#26]
Trying to understand what i'm doing wrong here... 

```
>>> email, username, password = 'info@info.xyz','blah','password'
>>> account = Account(email, username, password, debug=2, save=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'debug'
 
```

Removing debug and save parameters, gives a different error
```
>>> account = Account(email, username, password)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes 3 positional arguments but 4 were given
```

**Comment by trevorhobenshield** [comment]
Looks like you probably have an older version of the package.

Try pulling the latest version:
```bash
pip uninstall twitter-api-client -y
pip install twitter-api-client --no-cache-dir
```

**Comment by echan00** [comment]
Thanks I'm still having trouble. 

The version that is being installed is 0.4.7, is that correct?  I see here its 0.7.6? https://pypi.org/project/twitter-api-client/

```
% pip3 install twitter-api-client~=0.7.6

Defaulting to user installation because normal site-packages is not writeable
ERROR: Ignored the following versions that require a different python version: 0.4.5 Requires-Python >=3.11; 0.4.8 Requires-Python >=3.9.7; 0.4.9 Requires-Python >=3.9.7; 0.5.0 Requires-Python >=3.9.7; 0.5.1 Requires-Python >=3.9.7; 0.5.2 Requires-Python >=3.9.7; 0.5.3 Requires-Python >=3.9.7; 0.5.4 Requires-Python >=3.9.7; 0.5.5 Requires-Python >=3.9.7; 0.5.6 Requires-Python >=3.11.0; 0.5.7 Requires-Python >=3.9.7; 0.5.8 Requires-Python >=3.11.0; 0.5.9 Requires-Python >=3.11.0; 0.6.0 Requires-Python >=3.11.0; 0.6.1 Requires-Python >=3.11.0; 0.6.2 Requires-Python >=3.11.0; 0.6.3 Requires-Python >=3.11.0; 0.6.4 Requires-Python >=3.11.0; 0.6.5 Requires-Python >=3.11.0; 0.6.6 Requires-Python >=3.11.0; 0.6.7 Requires-Python >=3.11.0; 0.6.8 Requires-Python >=3.11.0; 0.6.9 Requires-Python >=3.11.0; 0.7.0 Requires-Python >=3.11.0; 0.7.1 Requires-Python >=3.11.0; 0.7.2 Requires-Python >=3.11.0; 0.7.3 Requires-Python >=3.11.0; 0.7.4 Requires-Python >=3.11.0; 0.7.5 Requires-Python >=3.11.0; 0.7.6 Requires-Python >=3.11.0
ERROR: Could not find a version that satisfies the requirement twitter-api-client~=0.7.6 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.6, 0.4.7)
ERROR: No matching distribution found for twitter-api-client~=0.7.6
```

**Comment by Ian-Bright** [comment]
Hey @trevorhobenshield having a similar issue and reinstalling did not fix

**Comment by guotie** [comment]
I installed the 0.5.7 version too

**Comment by guotie** [comment]
resolved.

It's the python version which cause installed low version twitter-api-client
