### ISSUE TITLE
Reply method doesn't work. Maybe should implement OAuth2Session.

### ISSUE THREAD

**Issue by yibudak** [trevorhobenshield/twitter-api-client#44]
Hello,

twitter is currently using the query_id **-tr9gsjcukmYZRN4dpYN8g** for reply and this query_id probably only works in oauth session. I can normally send tweets but not reply. does anyone have a solution for this? Can anyone reply with the query_id **7TKRKCPuAGsmYde0CudbVg**?

Current commit: [28cd391](https://github.com/trevorhobenshield/twitter-api-client/commit/28cd391b0612b3cba4308622ec8fd78cdf474675)

Output with new query_id:

`[success] xxxxx login success
2023-05-07 02:10:41,856.856 DEBUG: [403]
2023-05-07 02:10:41,856.856 DEBUG: https://twitter.com/i/api/graphql/-tr9gsjcukmYZRN4dpYN8g/CreateTweet`

Old query_id:

`[success] xxxxx login success
2023-05-07 02:12:06,529.529 DEBUG: [403]
2023-05-07 02:12:06,529.529 DEBUG: https://twitter.com/i/api/graphql/7TKRKCPuAGsmYde0CudbVg/CreateTweet`

**Comment by trevorhobenshield** [comment]
Can't replicate this issue, replies are still working as expected.

**Comment by yibudak** [comment]
It seems my issue was closed faster than a speeding bullet. Interesting. Here's another one for you to swiftly dismiss:

```python
[success] xxx login success
>>> account.reply('test', tweet_id=1660539698320637952)
2023-05-22 11:07:53,445.445 DEBUG: [403]
2023-05-22 11:07:53,445.445 DEBUG: https://twitter.com/i/api/graphql/7TKRKCPuAGsmYde0CudbVg/CreateTweet
2023-05-22 11:07:53,445.445 DEBUG: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yibudak/deneme/venv/lib/python3.11/site-packages/twitter/account.py", line 201, in reply
    return self.gql('POST', Operation.CreateTweet, variables)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yibudak/deneme/venv/lib/python3.11/site-packages/twitter/account.py", line 58, in gql
    save_data(r.json(), op, self.session.cookies.get('username', '_'))
              ^^^^^^^^
  File "/home/yibudak/deneme/venv/lib/python3.11/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>> 

```
