### ISSUE TITLE
Search function not working

### ISSUE THREAD

**Issue by trevtravtrev** [trevorhobenshield/twitter-api-client#8]
code:
```
from twitter.search import search

search(
        '(#dogs OR #cats) min_retweets:500',
    )
```

error:
```
2023-04-08 17:04:13,020.020 DEBUG: (#dogs OR #cats) min_retweets:500
2023-04-08 17:04:13,919.919 DEBUG: FAILED to combine search results, input length is 0: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\trevo\OneDrive\Desktop\twittertest\twittertest\main.py", line 31, in <module>
    main()
  File "C:\Users\trevo\OneDrive\Desktop\twittertest\twittertest\main.py", line 25, in main
    search(
  File "C:\Users\trevo\OneDrive\Desktop\twittertest\.venv\lib\site-packages\twitter\search.py", line 47, in search
    return asyncio.run(process(args, search_config, out_path))
  File "C:\Users\trevo\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\trevo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\trevo\OneDrive\Desktop\twittertest\.venv\lib\site-packages\twitter\search.py", line 53, in process
    return await asyncio.gather(*(paginate(q, s, config, out) for q in queries))
  File "C:\Users\trevo\OneDrive\Desktop\twittertest\.venv\lib\site-packages\twitter\search.py", line 67, in paginate
    (out / f'raw/{time.time_ns()}.json').write_text(orjson.dumps(data, option=orjson.OPT_INDENT_2).decode())
  File "C:\Users\trevo\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1155, in write_text
    return f.write(data)
  File "C:\Users\trevo\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f3e1' in position 284: character maps to <undefined>

Process finished with exit code 1

```

**Comment by trevorhobenshield** [comment]
All functions are still working, however Twitter has added another Arkose challenge after successful login. I've also been meaning to add some more helpful error messages and clean up the login flow (the successful login message is currently misleading, it still shows even when email or Arkose challenges are pending)

Almost all errors will be caused by security/anti-bot measures being enforced, such as an Arkose challenge, email verification, etc. The solution is to log in to the account normally in the browser and complete the challenges, switch to a different VPN, then log in again on the new VPN and ensure there are no pending challenges. You may need to try many different VPNs (sometimes all US ones get blocked) or residential ones.

![image](https://user-images.githubusercontent.com/59624054/230778826-a6573497-bce1-4c6c-8cc8-87a8698e2c49.png)

**Comment by bitcoin4cashqc** [comment]
Just a question, does this output as an exception or it's just debug, because I would that if this happen (it did a day ago and just going back on x trought my browser fixed), I would like to catch it and send a notification somewhere.
